baseurl = "https://winnipegaws.ca"
languageCode = "en-us"
title = "Winnipeg AWS User Group"
theme = "hugo-creative-theme"
# googleAnalytics = ""

[params]
	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Winnipeg AWS User Group"
	description = "Winnipeg's user group for everything AWS! Winnipeg AWS user group hosts meetups on a regular basis."

	# The path must be relative to the static folder
	favicon = "favicon.png"


	# Navigation
	[params.navigation]
		brand = "![Logo](/img/favicon.png)&nbsp;Winnipeg AWS User Group"

		[params.navigation.links]
			about     = "About"
			contact   = "Contact Us"
			events    = "Events"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Winnipeg AWS User Group"
		subtitle   = "Winnipeg's local AWS user group. From talks to workshops to chat rooms, you've come to the right place for everything AWS in Winnipeg."
		buttonText = "Connect with the community"

	# Service section
	[params.services]
		# headline = "Current Project"

      [[params.services.list]]
            icon = "fa-users"
            title = "Meetups"
            description = """
Regular meetups are held in central Winnipeg. To view past and upcoming events, visit our [events page](./events). You can also subscribe to our [mailing list](https://groups.google.com/forum/#!forum/winnipeg-aws-user-group) to be notified of future events.
            """

      [[params.services.list]]
          icon = "fa-heart"
          title = "Looking for Help?"
          description = "Want to chat? Join the [DC204 Slack Chat](https://thelongcon.ca/contact/) and visit the #orange-koolaid channel to connect with other Winnipeg AWS professionals. Our monthly meetups are another great way to ask questions and get answers: subscribe to [our mailing list](https://groups.google.com/forum/#!forum/winnipeg-aws-user-group) to be notified of future events."


	# About section
	[params.about]
		headline    = "About"
		description = "Founded in December 2018 in the wake of [The Long Con 2018](https://thelongcon.ca/2018/speakers/) in the [DC204 slack chat](https://thelongcon.ca/contact/), Winnipeg AWS has been hosting regular talks on a variety of AWS services for all skill levels, from prospective users all the way through to the seasoned expert."
		# buttonText  = "Get started!"

  #   # Portfolio modals
	# [params.portfolio.modal]
  #       client = "Client"
  #       date = "Date"
  #       category = "Category"
  #       buttonText = "Close"

  #   # Aside section
	# [params.aside]
	# 	headline = "Get the Creative Theme for Hugo"
  #   text = "TEXTYTEXT"

	# 	[params.aside.button]
	# 		text = "Download now"
	# 		link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Contact us"
		description = "You can reach us through the email below or feel free to join the [DC204 Slack Chat](https://thelongcon.ca/contact/) channel to get in contact with us. Our [mailing list](https://groups.google.com/forum/#!forum/winnipeg-aws-user-group) is also a great resource to email in and ask questions."
		email = "winnipegaws@gmail.com"
		facebook = "WinnipegAWS"
		twitter = "WinnipegAWS"
		mailing_list = "https://groups.google.com/forum/#!forum/winnipeg-aws-user-group"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
